version: 2

sources:
  - name: raw
    database: local-alignment-477812-b0
    schema: gz_raw_data

    tables:
      - name: raw_gz_sales
        alias: sales

      - name: raw_gz_product
        alias: product

      - name: raw_gz_ship
        alias: ship
